table gold_constructor_leaderboard
	lineageTag: 7fb96145-8066-4d90-802a-ee9d15ed27b7
	sourceLineageTag: [dbo].[gold_constructor_leaderboard]

	measure 'Team Color Hex' = MAX('gold_constructor_leaderboard'[Hex Color])
		lineageTag: 200c1e6b-fd0b-42f7-8a4d-8166c1cf68d4

		changedProperty = Name

		changedProperty = IsHidden

	column Team
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 65780104-76e9-4bec-b456-214cfdf40622
		sourceLineageTag: Team
		summarizeBy: none
		sourceColumn: Team

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Team Logo'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 750c2a50-9f64-40e2-8ef4-f6ac934996fd
		sourceLineageTag: Team_Logo
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Team_Logo

		changedProperty = Name

		changedProperty = DataCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Hex Color'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e947b766-7732-405d-a9d6-64afb4db8284
		sourceLineageTag: Hex_Color
		summarizeBy: none
		sourceColumn: Hex_Color

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b8fb32aa-421a-4d2b-8367-309aab88e9e9
		sourceLineageTag: Position
		summarizeBy: none
		sourceColumn: Position

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Points
		dataType: double
		sourceProviderType: real
		lineageTag: 1bc9802e-33ff-4a4e-a0b5-2faeab758438
		sourceLineageTag: Points
		summarizeBy: sum
		sourceColumn: Points

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Grand Prix'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e789b21e-e6d5-46fb-8209-17d14406bf1a
		sourceLineageTag: Grand_Prix
		summarizeBy: none
		sourceColumn: Grand_Prix
		sortByColumn: Date

		changedProperty = Name

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceProviderType: datetime2
		lineageTag: 66f45df3-c5c6-483b-8416-9781bae5137a
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Year
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 4b13133e-f1b7-4ea9-bba1-434225534271
		sourceLineageTag: Year
		summarizeBy: none
		sourceColumn: Year

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition gold_constructor_leaderboard = entity
		mode: directLake
		source
			entityName: gold_constructor_leaderboard
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

